language: c

before_install:
  - echo "deb http://dl.bintray.com/sba1/adtools-deb /" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y libcunit1-dev valgrind
  - sudo apt-get install -y --force-yes adtools-gcc

script: make -C tests
